### PR TITLE
Update assets build with production versions

### PR DESCRIPTION
**Pull request by teamon**

### CODE REVIEW

**Comment by teamon** [comment]
Forget it, it doesn't work...

**Comment by edgurgel** [comment]
OH hey @teamon what's the issue you are having?

**Comment by teamon** [comment]
Hey,

Latest release and current master have outdated scripts in priv - they do not work with MOUNT_PATH - this one is fixed already in web/static files.

Also, there are multiple js errors on queues and retries pages.
And "Delete all" on retries page does not work at all.

**Comment by edgurgel** [comment]
🤔  let me check this! Thanks for the report

**Comment by edgurgel** [comment]
I just released a new version 1.1.0 could you please try again? I ensured that priv/static was up-to-date etc. 🤞

**Comment by teamon** [comment]
Thanks! 
Socket can now correctly connect 🎉 

But delete all still does not work:
2017-09-21 at 13 16

**Comment by edgurgel** [comment]
We are getting there! I will investigate more. Thanks for the fast feedback!

**Comment by edgurgel** [comment]
@teamon I replicated the issue. Opening an issue to track this. We will definitely fix it soon. Thanks again!

**Pull request closed without merging**
