### PR TITLE
Use Jason instead of Poison

### PR DESCRIPTION
**Pull request by DiodonHystrix**
I noticed that this package is still using `Poison`, but recent `Phoenix` and `verk` are using `Jason`. So I updated the dependencies and configured `verk_web` to use `Jason`.

Also updated all other packages except `Timex`.

### CODE REVIEW

**Comment by edgurgel** [comment]
@DiodonHystrix that's awesome! I will release a new version soon 👍

**Comment by edgurgel** [comment]
Hey I was wondering if we should also include `jason` as a direct dependency? This way we won't have this indirect dependency and we won't depend on which version of verk is set etc? 

What do you think? :D

**Comment by DiodonHystrix** [comment]
Sure, why not. I can add it later today.

**Comment by DiodonHystrix** [comment]
Added.

**Comment by edgurgel** [comment]
Thanks once again! 🎉

**Pull request merged**
