### PR TITLE
added auth; upgraded to phoenix 1.2; fixed elixir 1.3 warnings

### PR DESCRIPTION
**Pull request by thousandsofthem**
* added auth; 
* upgraded to phoenix 1.2
* fixed elixir 1.3 warnings

Some details: https://github.com/edgurgel/verk_web/issues/24

### CODE REVIEW

**Comment by edgurgel** [comment]
Thank you very much, @thousandsofthem ! I will have look soon 👍

**Comment by edgurgel** [comment]
@thousandsofthem, do you think it would be possible to add also tests for the Auth module? I would be hesitant to have auth code with no tests. What do you reckon?

**Comment by thousandsofthem** [comment]
@edgurgel it's a plug and i have no idea how to test it. do you have recipes?

**Comment by edgurgel** [comment]
I've never done any tests using plug but searching for projects defining a plug I found this:

https://github.com/rbishop/plug_basic_auth/blob/master/test/plug_basic_auth_test.exs

We could either just do something similar or maybe consider using one of the available plugs to do basic auth?

I've found these 2 https://github.com/CultivateHQ/basic_auth & https://github.com/rbishop/plug_basic_auth

What do you think?

**Comment by thousandsofthem** [comment]
@edgurgel updated, please take a look. switched to `basic_auth`, added readme info.

**Comment by edgurgel** [comment]
Thank you! I will play with it and soon release a new version! Thank you very much!

**Pull request merged**
