### PR TITLE
Show retry time on Retries page

### PR DESCRIPTION
**Pull request by keyan**
Partially addresses #22

Relies on new release of Verk

This adds a column to the Retries page with the Unix time of the next job retry. Although we discussed formatting this on the frontend (I like MomentJS for this), I cannot for the life of me figure out Brunch and how to use JS within Phoenix templates. Perhaps someone can provide some help? Or maybe we could merge this PR and have the frontend work done downstream?

### CODE REVIEW

**Comment by edgurgel** [comment]
I wonder if we should for now just do `DateTime.to_unix(retry_at) |> DateTime.to_string` and show the date and time with UTC. It is probably more useful than the epoch time. What do you think?

**Comment by keyan** [comment]
@edgurgel, sorry for the delay. Didn't get to respond to this as soon as I hoped.

I originally had tried to add Timex but ran into some dependency conflict. I just tried again and it worked out fine. I added a commit that does the same thing we were hoping for from MomentJS.

Let me know what you think. If you'd rather just go with UTC time, then I'm okay with that too just in the interest of getting something out.

**Comment by keyan** [comment]
Here is how this looks now:

screen shot 2016-11-08 at 12 24 21 pm

**Comment by edgurgel** [comment]
This is awesome! Thank you very much! 👍

**Comment by edgurgel** [comment]
I will release a new version soon!

**Comment by edgurgel** [comment]
Something weird happened with the update of gettex:

```
UndefinedFunctionError at GET /retries
function Timex.Gettext.lgettext/3 is undefined or private. Did you mean one of:
```

**Comment by keyan** [comment]
Oh no! I'm running this branch in production and am not seeing any issues, but seeing as this is a documented issue I am surprised it didn't surface for me. I opened a PR that should address it for you: https://github.com/edgurgel/verk_web/pull/36

**Comment by edgurgel** [comment]
All good! Thanks again!

**Pull request merged**
